name: advance_math
description: Advance math is a comprehensive Dart library that enriches mathematical programming in Dart with a wide range of features beyond vectors and matrices. Offering functionality for complex numbers, advanced linear algebra, statistics, geometry, and more. The library opens up new possibilities for mathematical computation and data analysis. Whether you're developing a cutting-edge machine learning application, or simply need to perform calculations with complex numbers, it also provides the tools you need in a well-organized and easy-to-use package.
version: 1.0.0
repository: https://github.com/gameticharles/advance_math

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  buffer: ^1.2.0
  intl: ^0.18.1

dev_dependencies:
  benchmark_harness: ^2.2.2
  lints: ^2.0.0
  test: ^1.21.0
