name: advance_math
description: A robust Dart library for comprehensive mathematical programming. Offers complex numbers, algebra, statistics, angles, and geometry for diverse computations.
version: 3.3.4
repository: https://github.com/gameticharles/advance_math

environment:
  sdk: ^3.0.3

dependencies:
  buffer: ^1.2.2
  intl: ^0.18.1
  logging: ^1.2.0

dev_dependencies:
  benchmark_harness: ^2.2.2
  lints: ^2.1.1
  test: ^1.24.7
