name: advance_math
description: A robust Dart library for comprehensive mathematical programming. Offers complex numbers, algebra, statistics, angles, and geometry for diverse computations.
version: 3.1.0
repository: https://github.com/gameticharles/advance_math

environment:
  sdk: ^3.0.0

dependencies:
  buffer: ^1.2.0
  intl: ^0.18.0
  

dev_dependencies:
  logging: ^1.2.0
  benchmark_harness: ^2.2.2
  lints: ^2.0.0
  test: ^1.21.0
